@startuml classes
set namespaceSeparator none
class User {
    name: str
    interests: list[Tag]
    clubs: list[Club]
    friends: list[User]

    get_name() -> str
    set_name(name: str) -> None

    get_interests() -> list[Tag]
    set_interest(interests: list[Tag]) -> None

    get_clubs() -> list[Club]
    set_clubs(clubs: list[Club]) -> None

    get_friends() -> list[User]
    set_friends(friends: list[User]) -> None
}

class Club {
    name: str
    description: str
    members: int
    setting: str
    tags: list[Tag]
    chat: Chat
    calendar: Calendar

    get_name() -> str
    set_name(name: str) -> None
    
    get_description() -> str
    set_description(description: str) -> None

    get_members() -> int
    set_members(members: int) -> None

    get_setting() -> str
    set_setting(setting: str) -> None

    get_tags() -> list[Tag]
    set_tags(tags: list[Tag]) -> None

    get_chat() -> Chat
    set_chat(chat: Chat) -> None

    get_calendar() -> Calendar
    set_calendar(calendar: Calendar) -> None
}

class Tag {
    name: str

    get_name() -> str
    set_name(name: str) -> None
}

class Chat {
    logs: list[str]
    users: list[User]

    get_logs() -> list[str]
    set_logs(logs: list[str]) -> None

    get_users() -> list[User]
    set_users(users: list[User]) -> None
    add_message(message: str, user: User) -> None
}

class Calendar {
    reminders: list[str]

    get_reminders() -> list[str]
    set_reminders(reminders: list[str]) -> None
    add_reminder(reminder: str) -> None
    remove_reminder(reminder: str) -> None
}
@enduml