@startuml classes
set namespaceSeparator none
class User {
    name: str
    interests: list[Tag]
    clubs: list[Club]
    friends: list[User]

    add_User(name: str, interests: list[Tag], clubs: list[Club], friends: list[User]) -> None
    edit_User(name: str, interests: list[Tag], clubs: list[Club], friends: list[User]) -> None
    delete_User(name: str, interests: list[Tag], clubs: list[Club], friends: list[User]) -> None
    get_User(name: str, interests: list[Tag], clubs: list[Club], friends: list[User]) -> User
}

class Club {
    name: str
    description: str
    members: int
    setting: str
    tags: list[Tag]
    chat: Chat
    calendar: Calendar

    add_Club(name: str, description: str, members: int, setting: str, tags: list[Tag]) -> None
    edit_Club(name: str, description: str, members: int, setting: str, tags: list[Tag]) -> None
    delete_Club(name: str, description: str, members: int, setting: str, tags: list[Tag]) -> None
    get_Club(name: str, description: str, members: int, setting: str, tags: list[Tag]) -> Club
}
@enduml
