```plantuml
@startuml login
actor Users
boundary "System" as system
control "Sessions" as sessions
control "Authentication" as auth
Users -> system: Add Clubs
activate system
system -> auth: add_pipeline(club name, club description)
activate auth
auth --> system: True
deactivate auth
system -> sessions: add_new_session(add club to list)
activate sessions
sessions --> system: None
deactivate sessions
system -> system: redirect to home page
deactivate system
@enduml
```