```plantuml
@startuml login
actor Users
boundary "System" as system
control "Sessions" as sessions
control "Authentication" as auth
Users -> system: Logout
activate system
system -> auth: logout_pipeline(username, password)
activate auth
auth --> system: True
deactivate auth
system -> sessions: add_new_session(logout, add new account)
activate sessions
sessions --> system: None
deactivate sessions
system -> system: redirect to home page
deactivate system
@enduml
```