@startuml login
actor Users
boundary "System" as system
control "Sessions" as sessions
control "Authentication" as auth
Users -> system: Search Clubs
activate system
system -> auth: search_pipeline(search club name, search club description)
activate auth
auth --> system: True
deactivate auth
system -> sessions: add_new_session(show reults of club search)
activate sessions
sessions --> system: None
deactivate sessions
system -> system: redirect to home page
deactivate system
@enduml