@startuml login
actor Users
boundary "System" as system
control "Sessions" as sessions
control "Authentication" as auth
Users -> system: View Profile
activate system
system -> auth: view_pipeline(view clubs user is in, view personal info)
activate auth
auth --> system: True
deactivate auth
system -> sessions: add_new_session(edit Profile)
activate sessions
sessions --> system: None
deactivate sessions
system -> system: redirect to home page
deactivate system
@enduml